name: Python Build and Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: program
        path: main.py
  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: program
    - name: Run program
      run: |
        echo "1 2 3 4 5 0" | python main.py